### ISSUE TITLE
PR for New package to Void-packages was created

### ISSUE THREAD

**Issue by sinetoami** [owenthewizard/i3lockr#1]
@owenthewizard, sorry for the delay to create that PR [#7856](https://github.com/void-linux/void-packages/pull/7856). Thanks for this package! I have not tested yet. But I was able to install it. I'll come back if I find any problem. :+1:

**Comment by HadetTheUndying** [comment]
I'm getting an issue with

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by owenthewizard** [comment]
@HadetTheUndying

Please open a new issue. Build the `debug` version and run it with the RUST_BACKTRACE environment variable set to `1`.
