### ISSUE TITLE
Weird image artifacts with --icon on dual-monitor setup

### ISSUE THREAD

**Issue by jeffmakes** [owenthewizard/i3lockr#14]
**Describe The Bug**
When I have a second monitor plugged into my laptop, I get weird artifacts with --icon overlay. 

**To Reproduce** 
`i3lockr --blur 20 -u lock-icon.png `
with this png
![lock](https://user-images.githubusercontent.com/2532132/65840125-d38f3000-e30c-11e9-850f-32eeebf1e75c.png)

results in this weirdness
![s](https://user-images.githubusercontent.com/2532132/65840122-c8d49b00-e30c-11e9-9a6e-4ac1a7a90be7.png)

**System Info:**
 - Fedora 30, plain i3
`i3lock: version 2.12-3-gf6e0218 (2019-09-27, branch "master") © 2010 Michael Stapelberg`
`i3lockr v1.0.0-final compiled for 'x86_64-unknown-linux-gnu' at 1569792999 (master@0cb4018)`
- Laptop with external monitor connected over DisplayPort, different resolution from laptop panel.
```
$ xrandr --listmonitors 
Monitors: 2
 0: +*DP-1 2560/677x1080/290+0+0  DP-1
 1: +eDP-1 1920/309x1080/173+0+1080  eDP-1
```

**Additional context**
The overlay is on the primary monitor, as desired.

**Comment by owenthewizard** [comment]
As a temporary workaround, have you tried using the `--ignore-monitors` argument with one of the monitors?

**Comment by jeffmakes** [comment]
Ah, nice workaround, that does get rid of the artifacts. I assumed it would leave the other monitor white/black but it applies the blur effect and looks fine. I can live without the lock symbol on both monitors.

**Comment by owenthewizard** [comment]
Can you try testing the `develop` branch?

**Comment by jeffmakes** [comment]
Ok, that's fixed the artifacts nicely. Looks a lot better, but the icon placement isn't quite right. Unfortunately my screens are now in a different configuration, and I couldn't change the layout because xrandr is the work of satan. Let me know if you'd like to see it in the placement I used before and I'll reboot :D

![i3l](https://user-images.githubusercontent.com/2532132/67709887-2c5ef080-f9bf-11e9-8d52-b84f7c7accd3.png)

**Comment by owenthewizard** [comment]
I'd be interested in the output of `xrandr` in the current configuration as well as the output of `i3lockr `**`-v`**` --blur 20 -u lock-icon.png `. Placement as before on dev branch would be good to see as well.

**Comment by jeffmakes** [comment]
[i3lockr.txt](https://github.com/owenthewizard/i3lockr/files/3780825/i3lockr.txt)
[xrandr.txt](https://github.com/owenthewizard/i3lockr/files/3780826/xrandr.txt)
Logs ^^^.
I'll reboot, change the placement and do it again...

**Comment by jeffmakes** [comment]
![i3l](https://user-images.githubusercontent.com/2532132/67721898-f417dc00-f9d7-11e9-808a-c2ea904fbbf0.png)
[i3lockr.txt](https://github.com/owenthewizard/i3lockr/files/3780850/i3lockr.txt)
[xrandr.txt](https://github.com/owenthewizard/i3lockr/files/3780851/xrandr.txt)

**Comment by jeffmakes** [comment]
Sorry, accidentally closed the issue there!
Right, previous post is close to the original placement, though I've realised that I was actually using a different monitor before, as you can see from the size of the two monitors. 
I didn't need to reboot - I had srandrd running, which was clobbering my attempts to rearrange things.

**Comment by owenthewizard** [comment]
Would you mind testing the latest commit? Driver issues with my laptop are preventing me from testing with multiple monitors :frowning_face:.

**Comment by oedm** [comment]
I could test successfully your last commit. Works for me. :+1: 

master branch:
![master](https://user-images.githubusercontent.com/36274628/72523883-0845d980-3861-11ea-96f4-e50ecc06959c.png)

develop branch
![develop](https://user-images.githubusercontent.com/36274628/72523893-0bd96080-3861-11ea-84d4-075b49937ead.png)

**Comment by owenthewizard** [comment]
Excellent, closing this issue and will merge `develop` into `master` soon.
