### ISSUE TITLE
xcb-util version update

### ISSUE THREAD

**Issue by Darkasf** [owenthewizard/i3lockr#9]
xcb-util needs to be updated to v0.2.1 from 0.2.0

**Comment by JohnAZoidberg** [comment]
Would you like to make a PR and test whether the new version still works fine?

**Comment by Darkasf** [comment]
It didn't actually end up working for me so I went back to i3lock-next for the time being. The `--raw` option with the resolution was breaking i3lock altogether, after removing that it worked but probably the path to the image was wrong because the default white was displayed.

**Comment by JohnAZoidberg** [comment]
Did you build i3lock from git? Their latest release is too old for i3lockr.

**Comment by Darkasf** [comment]
Compiling i3lock from git fixed the issue, but the image isn't blurred

**Comment by Darkasf** [comment]
Actually it looks like all image manipulation is missing since the instead of the lock image it's just the default i3lock circle that's there

**Comment by JohnAZoidberg** [comment]
Try to build it from the v2 branch and run it with a higher blur factor like `i3lockr -b 10`.
I don't think the i3lockr image is included by default.

**Comment by JohnAZoidberg** [comment]
@owenthewizard Do you want to make the `v2` branch the default? Or merge it into master?
It seems to be a lot better than master and you don't have lots of legacy users that depend on an unchanged master ;)

**Comment by Darkasf** [comment]
The v2 branch dropped the image but it ended up working. Thank you for your time!

**Comment by owenthewizard** [comment]
@JohnAZoidberg Yes I've been meaning to, I'll do that today.

**Comment by owenthewizard** [comment]
Done!
